import streamlit as st
from PIL import Image
import matplotlib.pyplot as plt

from inference import predict

from utils.mapping import DISEASE_NAMES
from utils.mapping import CLASS_TO_DISEASE

# ==========================
# Page Configuration
# ==========================

st.set_page_config(
    page_title="Skin Disease Classifier",
    page_icon="🩺",
    layout="centered"
)

# ==========================
# Sidebar
# ==========================

st.sidebar.title("🩺 About Project")

st.sidebar.markdown("""
### 🤖 Model
**ResNet50 (Fine-Tuned)**

### 📂 Dataset
HAM10000

### 🧬 Classes
7 Skin Diseases

### ⚙️ Framework
TensorFlow + Streamlit
""")

st.sidebar.markdown("---")
st.sidebar.write("Developed by **Deepak Kumar**")

# ==========================
# Main Title
# ==========================

st.title("🩺 Skin Disease Classification")

st.write(
    "Upload a skin lesion image and let the AI model predict the disease."
)

# ==========================
# File Upload
# ==========================

upload_file = st.file_uploader(
    "Upload an Image",
    type=["jpg", "jpeg", "png"]
)

# ==========================
# Prediction
# ==========================

if upload_file is not None:

    image = Image.open(upload_file)

    temp_path = "temp.jpg"

    image.save(temp_path)

    st.image(
        image,
        caption="Uploaded Image",
        use_container_width=True
    )

    if st.button(
        "🔍 Predict Disease",
        use_container_width=True,
        type="primary"
    ):

        with st.spinner("🔬 AI model is analyzing the image..."):

            result = predict(temp_path)

        col1, col2 = st.columns([1, 1])

        # ==========================
        # Left Column
        # ==========================

        with col1:

            st.image(
                image,
                caption="Uploaded Image",
                use_container_width=True
            )

        # ==========================
        # Right Column
        # ==========================

        with col2:

            st.success(
                f"✅ Predicted Disease : {result['disease_name']}"
            )

            st.metric(
                label="Model Confidence",
                value=f"{result['confidence']*100:.2f}%"
            )

            st.progress(result["confidence"])

            if result["confidence"] < 0.60:

                st.warning(
                    "⚠️ Model confidence is low. Please interpret the prediction carefully."
                )

            st.subheader("📋 Disease Description")

            st.info(result["description"])

            st.subheader("🏆 Top 3 Predictions")

            medals = ["🥇", "🥈", "🥉"]

            for medal, item in zip(medals, result["top3"]):

                st.write(
                    f"{medal} **{item['disease_name']}** "
                    f"({item['confidence']*100:.2f}%)"
                )

        # ==========================
        # Probability Chart
        # ==========================

        st.divider()

        st.subheader("📊 Prediction Probability")

        class_names = [

            DISEASE_NAMES[CLASS_TO_DISEASE[i]]

            for i in range(len(CLASS_TO_DISEASE))

        ]

        fig, ax = plt.subplots(figsize=(10, 4))

        bars = ax.bar(
            class_names,
            result["probabilities"]
        )

        ax.set_ylim(0, 1)

        ax.set_ylabel("Probability")

        ax.set_xlabel("Disease")

        ax.set_title("Prediction Probability")

        plt.xticks(rotation=30, ha="right")

        # Probability values on top of bars
        for bar in bars:

            height = bar.get_height()

            ax.text(
                bar.get_x() + bar.get_width() / 2,
                height + 0.02,
                f"{height:.2f}",
                ha="center",
                fontsize=9
            )

        st.pyplot(fig)

        # ==========================
        # Disclaimer
        # ==========================

        st.divider()

        st.warning(
            """
⚠️ **Medical Disclaimer**

This prediction is generated by an AI model for educational purposes only.

It should **NOT** be considered as a medical diagnosis.

Please consult a qualified dermatologist before making any medical decision.
"""
        )